avahuer_web_homepage:
    pattern:  /
    defaults: { _controller: AvahuerWebBundle:Default:index }

avahuer_web_contacto:
    pattern:  /contacto
    defaults: { _controller: AvahuerWebBundle:Default:contacto }

avahuer_web_empresa:
    pattern:  /empresa
    defaults: { _controller: AvahuerWebBundle:Default:empresa }